-- Initial Database Schema for SPECTRE Inventory System
-- SPECTRE POS & Inventory Management
-- Version: 1.0
-- Date: 2026-06-15

-- ============================================
-- CORE TABLES
-- ============================================

-- Products Table
-- Note: If table already exists with bigint id, this will not recreate it
CREATE TABLE IF NOT EXISTS products (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nama_barang TEXT NOT NULL,
    kategori TEXT NOT NULL,
    ukuran TEXT,
    harga_jual NUMERIC NOT NULL CHECK (harga_jual >= 0),
    harga_member NUMERIC CHECK (harga_member >= 0),
    harga_modal NUMERIC NOT NULL CHECK (harga_modal >= 0),
    stok INTEGER NOT NULL DEFAULT 0 CHECK (stok >= 0),
    sku TEXT UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Members Table
CREATE TABLE IF NOT EXISTS members (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nama TEXT NOT NULL,
    nomor_telepon TEXT UNIQUE NOT NULL,
    email TEXT,
    alamat TEXT,
    poin INTEGER DEFAULT 0 CHECK (poin >= 0),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Payments Table (POS Sales)
-- Note: If table already exists with TEXT id, this will not recreate it
CREATE TABLE IF NOT EXISTS payments (
    id TEXT PRIMARY KEY,
    invoice_number TEXT UNIQUE NOT NULL,
    buyer TEXT NOT NULL,
    product TEXT NOT NULL,
    jumlah INTEGER NOT NULL CHECK (jumlah > 0),
    total_harga NUMERIC NOT NULL CHECK (total_harga >= 0),
    paid_amount NUMERIC DEFAULT 0 CHECK (paid_amount >= 0),
    remaining_amount NUMERIC DEFAULT 0 CHECK (remaining_amount >= 0),
    method TEXT NOT NULL, -- Cash, Transfer, QRIS, etc.
    status TEXT NOT NULL CHECK (status IN ('pending', 'partial', 'paid', 'cancelled')),
    confirmed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Sales History Table
CREATE TABLE IF NOT EXISTS sales_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    payment_id TEXT NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    nama_barang TEXT NOT NULL,
    kategori TEXT,
    ukuran TEXT,
    jumlah INTEGER NOT NULL CHECK (jumlah > 0),
    total_harga NUMERIC NOT NULL CHECK (total_harga >= 0),
    tipe_pembeli TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Expenses Table
CREATE TABLE IF NOT EXISTS expenses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    kategori TEXT NOT NULL,
    deskripsi TEXT,
    nominal NUMERIC NOT NULL CHECK (nominal >= 0),
    tanggal DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- AUTHENTICATION & USER MANAGEMENT
-- ============================================

-- Profiles Table (Supabase Auth extension)
CREATE TABLE IF NOT EXISTS profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE,
    full_name TEXT,
    role TEXT NOT NULL CHECK (role IN ('ADMIN', 'CASHIER')) DEFAULT 'CASHIER',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- MARKPLACE INTEGRATION
-- ============================================

-- Marketplace Accounts Table
CREATE TABLE IF NOT EXISTS marketplace_accounts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    platform TEXT NOT NULL CHECK (platform IN ('SHOPEE', 'TIKTOK', 'TOKOPEDIA', 'LAZADA')),
    account_name TEXT NOT NULL,
    shop_id TEXT,
    api_key TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Online Orders Table
CREATE TABLE IF NOT EXISTS online_orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    marketplace_account_id UUID REFERENCES marketplace_accounts(id) ON DELETE SET NULL,
    order_number TEXT NOT NULL,
    platform_order_id TEXT,
    platform TEXT NOT NULL,
    order_date TIMESTAMP WITH TIME ZONE NOT NULL,
    customer_name TEXT,
    customer_phone TEXT,
    customer_address TEXT,
    order_status TEXT NOT NULL CHECK (order_status IN ('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED')),
    gross_sales NUMERIC DEFAULT 0 CHECK (gross_sales >= 0),
    platform_fee NUMERIC DEFAULT 0 CHECK (platform_fee >= 0),
    shipping_fee NUMERIC DEFAULT 0 CHECK (shipping_fee >= 0),
    net_revenue NUMERIC GENERATED ALWAYS AS (gross_sales - platform_fee - shipping_fee) STORED,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Order Items Table
CREATE TABLE IF NOT EXISTS order_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    online_order_id UUID NOT NULL REFERENCES online_orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
    product_name TEXT NOT NULL,
    sku TEXT,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC NOT NULL CHECK (unit_price >= 0),
    discount NUMERIC DEFAULT 0 CHECK (discount >= 0),
    tax NUMERIC DEFAULT 0 CHECK (tax >= 0),
    total_price NUMERIC GENERATED ALWAYS AS ((quantity * unit_price) - COALESCE(discount, 0) + COALESCE(tax, 0)) STORED,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Marketplace Fees Table
CREATE TABLE IF NOT EXISTS marketplace_fees (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    online_order_id UUID NOT NULL REFERENCES online_orders(id) ON DELETE CASCADE,
    fee_type TEXT NOT NULL, -- COMMISSION, TRANSACTION_FEE, SERVICE_FEE, SHIPPING_FEE
    fee_name TEXT NOT NULL,
    fee_amount NUMERIC NOT NULL CHECK (fee_amount >= 0),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Settlements Table
CREATE TABLE IF NOT EXISTS settlements (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    marketplace_account_id UUID NOT NULL REFERENCES marketplace_accounts(id) ON DELETE CASCADE,
    settlement_id TEXT UNIQUE NOT NULL,
    settlement_date DATE NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    total_amount NUMERIC NOT NULL CHECK (total_amount >= 0),
    fee_amount NUMERIC DEFAULT 0 CHECK (fee_amount >= 0),
    net_amount NUMERIC GENERATED ALWAYS AS (total_amount - fee_amount) STORED,
    status TEXT NOT NULL CHECK (status IN ('PENDING', 'RECEIVED', 'RECONCILED')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- RETURNS & REFUNDS
-- ============================================

-- Returns Table
CREATE TABLE IF NOT EXISTS returns (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    payment_id TEXT NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    reason TEXT NOT NULL,
    return_type TEXT NOT NULL CHECK (return_type IN ('refund', 'exchange')),
    refund_amount NUMERIC DEFAULT 0 CHECK (refund_amount >= 0),
    notes TEXT,
    status TEXT NOT NULL CHECK (status IN ('pending', 'processed', 'cancelled')) DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    processed_at TIMESTAMP WITH TIME ZONE,
    cancelled_at TIMESTAMP WITH TIME ZONE
);

-- ============================================
-- DISCOUNTS & PROMOTIONS
-- ============================================

-- Discounts Table
CREATE TABLE IF NOT EXISTS discounts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('percentage', 'fixed', 'buy_x_get_y')),
    value NUMERIC NOT NULL CHECK (value >= 0),
    min_purchase NUMERIC DEFAULT 0 CHECK (min_purchase >= 0),
    max_discount NUMERIC CHECK (max_discount >= 0),
    applicable_products UUID[], -- Array of product IDs
    applicable_categories TEXT[], -- Array of category names
    promo_code TEXT UNIQUE,
    start_date TIMESTAMP WITH TIME ZONE NOT NULL,
    end_date TIMESTAMP WITH TIME ZONE NOT NULL,
    max_uses INTEGER CHECK (max_uses > 0),
    used_count INTEGER DEFAULT 0 CHECK (used_count >= 0),
    member_only BOOLEAN DEFAULT false,
    active BOOLEAN DEFAULT true,
    buy_quantity INTEGER CHECK (buy_quantity > 0), -- For buy_x_get_y
    get_quantity INTEGER CHECK (get_quantity > 0), -- For buy_x_get_y
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- INDEXES FOR PERFORMANCE
-- ============================================

-- Products Indexes
CREATE INDEX IF NOT EXISTS idx_products_sku ON products(sku);
CREATE INDEX IF NOT EXISTS idx_products_kategori ON products(kategori);
CREATE INDEX IF NOT EXISTS idx_products_stok ON products(stok);

-- Payments Indexes
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status);
CREATE INDEX IF NOT EXISTS idx_payments_invoice ON payments(invoice_number);
CREATE INDEX IF NOT EXISTS idx_payments_created_at ON payments(created_at);

-- Sales History Indexes
CREATE INDEX IF NOT EXISTS idx_sales_history_payment_id ON sales_history(payment_id);
CREATE INDEX IF NOT EXISTS idx_sales_history_product_id ON sales_history(product_id);
CREATE INDEX IF NOT EXISTS idx_sales_history_created_at ON sales_history(created_at);

-- Expenses Indexes
CREATE INDEX IF NOT EXISTS idx_expenses_kategori ON expenses(kategori);
CREATE INDEX IF NOT EXISTS idx_expenses_tanggal ON expenses(tanggal);

-- Marketplace Indexes
-- Add platform column if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'online_orders' AND column_name = 'platform'
    ) THEN
        ALTER TABLE online_orders ADD COLUMN platform TEXT;
    END IF;
END $$;

-- Add order_status column if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'online_orders' AND column_name = 'order_status'
    ) THEN
        ALTER TABLE online_orders ADD COLUMN order_status TEXT;
    END IF;
END $$;

-- Add order_date column if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'online_orders' AND column_name = 'order_date'
    ) THEN
        ALTER TABLE online_orders ADD COLUMN order_date TIMESTAMP WITH TIME ZONE;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_online_orders_platform ON online_orders(platform);
CREATE INDEX IF NOT EXISTS idx_online_orders_status ON online_orders(order_status);
CREATE INDEX IF NOT EXISTS idx_online_orders_date ON online_orders(order_date);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(online_order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product_id ON order_items(product_id);

-- Returns Indexes
CREATE INDEX IF NOT EXISTS idx_returns_status ON returns(status);
CREATE INDEX IF NOT EXISTS idx_returns_payment_id ON returns(payment_id);

-- Discounts Indexes
CREATE INDEX IF NOT EXISTS idx_discounts_active ON discounts(active);
CREATE INDEX IF NOT EXISTS idx_discounts_promo_code ON discounts(promo_code);
CREATE INDEX IF NOT EXISTS idx_discounts_dates ON discounts(start_date, end_date);

-- ============================================
-- TRIGGERS FOR AUTOMATED UPDATES
-- ============================================

-- Update updated_at timestamp function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply updated_at triggers to relevant tables
DROP TRIGGER IF EXISTS update_products_updated_at ON products;
CREATE TRIGGER update_products_updated_at BEFORE UPDATE ON products
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_members_updated_at ON members;
CREATE TRIGGER update_members_updated_at BEFORE UPDATE ON members
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_payments_updated_at ON payments;
CREATE TRIGGER update_payments_updated_at BEFORE UPDATE ON payments
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_expenses_updated_at ON expenses;
CREATE TRIGGER update_expenses_updated_at BEFORE UPDATE ON expenses
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_marketplace_accounts_updated_at ON marketplace_accounts;
CREATE TRIGGER update_marketplace_accounts_updated_at BEFORE UPDATE ON marketplace_accounts
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_online_orders_updated_at ON online_orders;
CREATE TRIGGER update_online_orders_updated_at BEFORE UPDATE ON online_orders
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_settlements_updated_at ON settlements;
CREATE TRIGGER update_settlements_updated_at BEFORE UPDATE ON settlements
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_discounts_updated_at ON discounts;
CREATE TRIGGER update_discounts_updated_at BEFORE UPDATE ON discounts
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================

-- Enable RLS on all tables
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE members ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE marketplace_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE online_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE marketplace_fees ENABLE ROW LEVEL SECURITY;
ALTER TABLE settlements ENABLE ROW LEVEL SECURITY;
ALTER TABLE returns ENABLE ROW LEVEL SECURITY;
ALTER TABLE discounts ENABLE ROW LEVEL SECURITY;

-- Products RLS
CREATE POLICY "Admins can do anything on products" ON products
    FOR ALL USING (auth.role() = 'authenticated' AND 
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'ADMIN'));

CREATE POLICY "Cashiers can read products" ON products
    FOR SELECT USING (auth.role() = 'authenticated' AND 
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'CASHIER'));

-- Members RLS
CREATE POLICY "Admins can do anything on members" ON members
    FOR ALL USING (auth.role() = 'authenticated' AND 
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'ADMIN'));

CREATE POLICY "Cashiers can read members" ON members
    FOR SELECT USING (auth.role() = 'authenticated' AND 
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'CASHIER'));

-- Payments RLS
CREATE POLICY "Admins can do anything on payments" ON payments
    FOR ALL USING (auth.role() = 'authenticated' AND 
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'ADMIN'));

CREATE POLICY "Cashiers can read payments" ON payments
    FOR SELECT USING (auth.role() = 'authenticated' AND 
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'CASHIER'));

CREATE POLICY "Cashiers can insert payments" ON payments
    FOR INSERT WITH CHECK (auth.role() = 'authenticated' AND 
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'CASHIER'));

CREATE POLICY "Cashiers can update payments" ON payments
    FOR UPDATE USING (auth.role() = 'authenticated' AND 
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'CASHIER'));

-- Sales History RLS
CREATE POLICY "Admins can do anything on sales_history" ON sales_history
    FOR ALL USING (auth.role() = 'authenticated' AND 
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'ADMIN'));

CREATE POLICY "Cashiers can read sales_history" ON sales_history
    FOR SELECT USING (auth.role() = 'authenticated' AND 
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'CASHIER'));

-- Expenses RLS
CREATE POLICY "Admins can do anything on expenses" ON expenses
    FOR ALL USING (auth.role() = 'authenticated' AND 
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'ADMIN'));

CREATE POLICY "Cashiers can read expenses" ON expenses
    FOR SELECT USING (auth.role() = 'authenticated' AND 
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'CASHIER'));

-- Profiles RLS
CREATE POLICY "Users can read own profile" ON profiles
    FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Admins can do anything on profiles" ON profiles
    FOR ALL USING (auth.role() = 'authenticated' AND 
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'ADMIN'));

-- Marketplace Tables RLS (Admin only for now)
CREATE POLICY "Admins can do anything on marketplace_accounts" ON marketplace_accounts
    FOR ALL USING (auth.role() = 'authenticated' AND 
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'ADMIN'));

CREATE POLICY "Admins can do anything on online_orders" ON online_orders
    FOR ALL USING (auth.role() = 'authenticated' AND 
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'ADMIN'));

CREATE POLICY "Admins can do anything on order_items" ON order_items
    FOR ALL USING (auth.role() = 'authenticated' AND 
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'ADMIN'));

CREATE POLICY "Admins can do anything on marketplace_fees" ON marketplace_fees
    FOR ALL USING (auth.role() = 'authenticated' AND 
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'ADMIN'));

CREATE POLICY "Admins can do anything on settlements" ON settlements
    FOR ALL USING (auth.role() = 'authenticated' AND 
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'ADMIN'));

-- Returns RLS
CREATE POLICY "Admins can do anything on returns" ON returns
    FOR ALL USING (auth.role() = 'authenticated' AND 
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'ADMIN'));

CREATE POLICY "Cashiers can read returns" ON returns
    FOR SELECT USING (auth.role() = 'authenticated' AND 
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'CASHIER'));

-- Discounts RLS
CREATE POLICY "Admins can do anything on discounts" ON discounts
    FOR ALL USING (auth.role() = 'authenticated' AND 
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'ADMIN'));

CREATE POLICY "Cashiers can read active discounts" ON discounts
    FOR SELECT USING (auth.role() = 'authenticated' AND 
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'CASHIER') AND active = true);

-- ============================================
-- MIGRATION COMPLETE
-- ============================================

-- Verification queries (run these to verify migration success)
-- SELECT COUNT(*) FROM products;
-- SELECT COUNT(*) FROM members;
-- SELECT COUNT(*) FROM payments;
-- SELECT COUNT(*) FROM sales_history;
-- SELECT COUNT(*) FROM expenses;
-- SELECT COUNT(*) FROM profiles;
-- SELECT COUNT(*) FROM marketplace_accounts;
-- SELECT COUNT(*) FROM online_orders;
-- SELECT COUNT(*) FROM order_items;
-- SELECT COUNT(*) FROM marketplace_fees;
-- SELECT COUNT(*) FROM settlements;
-- SELECT COUNT(*) FROM returns;
-- SELECT COUNT(*) FROM discounts;
